FROM pytorch/pytorch:2.6.0-cuda12.6-cudnn9-runtime

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY app app
COPY requirements-gpu.txt /app

RUN pip install --no-cache-dir -r requirements-gpu.txt
RUN rm -fr requirements-gpu.txt && \
    rm -fr app/api/routes-tesseract.py

EXPOSE 8080

CMD [ "bash" ]
