FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-spa \
    tesseract-ocr-fas \
    tesseract-ocr-ara \
    tesseract-ocr-fra \
    tesseract-ocr-deu \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc/*

WORKDIR /app

COPY app/api app/api
COPY requirements-cpu.txt /app

RUN pip install --no-cache-dir -r requirements-cpu.txt
RUN rm -fr requirements-cpu.txt && \
    rm -fr app/api/routes-deepseek.py

EXPOSE 8080

CMD [ "bash" ]
